## Settings
title: CV
owner: "Christian"
url: "https://marbelvega.github.io"
baseurl: "/"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "adm_christian_vega@outlook.com"
github: "MarbelVega"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed by christian, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 4
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"